name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - opencv
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - pip
  - pip:
      - mediapipe==0.10.5
